In [7]:
# Q1. Array Creation and Manipulation:

# Create different types of arrays (1D, 2D, 3D) using various methods (np.array, np.arange, np.linspace, etc.).

print("1D Array \n")
import numpy as np
arr_1d = np.array([11, 22, 33, 44, 55])
print(arr_1d)

arr_arange = np.arange(1, 10, 2)
print(arr_arange)

arr_lin = np.linspace(0, 1, 5)
print(arr_lin)

print("\n2D Array \n")
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d)

print("\n3D Array \n")
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr_3d)

# Perform basic operations on arrays (indexing, slicing, reshaping, concatenation).
print(arr_1d[3])        # Accessing element at index 3
print(arr_1d[1:3])      # Slicing elements from index 1 to 2

print(arr_2d[0, 2])     # Accessing element at row 0, column 2
print(arr_2d[:, 1])     # Accessing all rows for column 1

print(arr_3d[0, 0, 1])  # Accessing element in the first matrix, first row, second column

arr_concat_1d = np.concatenate([arr_1d, arr_arange]) # cocatenation

# Investigate array attributes like shape, size, dtype, ndim.
print(arr_2d.shape)  # Returns the shape (rows, columns) of the array
print(arr_2d.size)  # Returns the total number of elements in the array
print(arr_2d.dtype)  # Returns the data type of the array elements
print(arr_3d.ndim)  # Returns the number of dimensions of the array

# Use methods like reshape, resize, flatten

arr_reshaped = arr_1d.reshape(5, 1)  # Reshape 1D array to 2D array with 5 rows and 1 column
arr_resized = np.resize(arr_1d, (3, 2))  # Resize to a 3x2 array, repeating elements if necessary
arr_flattened = arr_2d.flatten()  # Flatten 2D array to 1D array

1D Array 

[11 22 33 44 55]
[1 3 5 7 9]
[0.   0.25 0.5  0.75 1.  ]

2D Array 

[[1 2 3]
 [4 5 6]
 [7 8 9]]

3D Array 

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
44
[22 33]
3
[2 5 8]
2
(3, 3)
9
int32
3


In [25]:
# Q2. Data Loading and Preprocessing:

# Load a dataset (e.g., CSV, Excel) using NumPy.
import numpy as np

# Load a CSV file
data = np.genfromtxt('loan_data_train.csv', delimiter=',', skip_header=1)
print(data)

# Clean and preprocess the data (handling missing values, normalization, standardization).
missing_values = np.isnan(data)
col_mean = np.nanmean(data, axis=0)
indices = np.where(np.isnan(data))
data[indices] = np.take(col_mean, indices[1])

print("\nNormalization\n")
data_min = np.min(data, axis=0)
data_max = np.max(data, axis=0)
data_normalized = (data - data_min) / (data_max - data_min)
print(data_normalized)

print("\nStandardization\n")
data_mean = np.mean(data, axis=0)
data_std = np.std(data, axis=0)
data_standardized = (data - data_mean) / data_std

#Calculate mean, median, standard deviation, variance, and other statistical measures.
mean = np.mean(data, axis=0)  # Mean of each column
median = np.median(data, axis=0)  # Median of each column
std_dev = np.std(data, axis=0)  # Standard deviation of each column
variance = np.var(data, axis=0)  # Variance of each column

min_values = np.min(data, axis=0)
max_values = np.max(data, axis=0)
sum_values = np.sum(data, axis=0)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)
print("Variance:", variance)
print("Min:", min_values)
print("Max:", max_values)
print("Sum:", sum_values)

[[7.9542e+04        nan        nan ...        nan 3.0000e+00        nan]
 [7.5473e+04        nan        nan ...        nan 3.0000e+00        nan]
 [6.7265e+04        nan        nan ...        nan 1.0000e+00        nan]
 ...
 [9.4545e+04        nan        nan ...        nan 3.0000e+00        nan]
 [5.3635e+04        nan        nan ...        nan 2.0000e+00        nan]
 [6.7953e+04        nan        nan ...        nan 0.0000e+00        nan]]

Normalization

[[0.76332156        nan        nan ...        nan 0.33333333        nan]
 [0.72426866        nan        nan ...        nan 0.33333333        nan]
 [0.64549102        nan        nan ...        nan 0.11111111        nan]
 ...
 [0.90731534        nan        nan ...        nan 0.33333333        nan]
 [0.51467483        nan        nan ...        nan 0.22222222        nan]
 [0.65209421        nan        nan ...        nan 0.                nan]]

Standardization

Mean: [5.20242565e+04            nan            nan            nan
           

C:\Users\aditi\AppData\Local\Temp\ipykernel_756\4173154803.py:12: RuntimeWarning: Mean of empty slice
  col_mean = np.nanmean(data, axis=0)
